### ISSUE TITLE
Remove duplicate, broken lab (js-principles-scope-chain-code-along)

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/flatiron-curriculum-online-proposals#2]
Dozens of issues related to this:
![issues](http://curriculum-content.s3.amazonaws.com/github-media/js-principles-scope-chain-code-along-issues.png)

Needs to be excluded in the next deploy and destroyed.

**Comment by sgharms** [comment]
Targeted for v7 release.

**Comment by maxwellbenton** [comment]
Staged for v7
